# Generated by Django 3.2.13 on 2023-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField(verbose_name='Номер студента')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя студента')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия студента')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('field_of_study', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ('student_number',),
            },
        ),
    ]
