# Generated by Django 3.2.13 on 2023-06-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(verbose_name='Средний балл'),
        ),
    ]
