# Generated by Django 3.2.13 on 2023-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20230605_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(verbose_name='Номер студента'),
        ),
    ]
